// Hand-authored 5-panel-high glyph library.
// Edit these rows directly to tune the lettering against the YES TECH sample sheet.
// Simple glyphs use string rows. Tricky glyphs can use explicit panel coordinates:
// { width, height, panels: [{ token, x, y }] } where x/y are in panel units and can use 0.5 offsets.
//
// Token legend:
// . = empty
// S = MG9 square
// A = MG12 triangle, right angle at bottom-left
// B = MG12 triangle, right angle at top-left
// C = MG12 triangle, right angle at top-right
// D = MG12 triangle, right angle at bottom-right
// a = MG13 quarter-circle, rounded top-left
// b = MG13 quarter-circle, rounded top-right
// c = MG13 quarter-circle, rounded bottom-right
// d = MG13 quarter-circle, rounded bottom-left

window.REFERENCE_SAMPLE_TEXT = `123456789
ABCDEFGHI
JKLMNOPQR
STUVWXYZ`;

window.GLYPH_TOKEN_MAP = {
  S: { type: "MG9", rotation: 0 },
  A: { type: "MG12", rotation: 0 },
  B: { type: "MG12", rotation: 90 },
  C: { type: "MG12", rotation: 180 },
  D: { type: "MG12", rotation: 270 },
  a: { type: "MG13", rotation: 0 },
  b: { type: "MG13", rotation: 90 },
  c: { type: "MG13", rotation: 180 },
  d: { type: "MG13", rotation: 270 },
};

window.GLYPH_LIBRARY = {
  "0": ["aSSb", "S..S", "S..S", "S..S", "dSSc"],
  "1": ["S", "S", "S", "S", "S"],
  "2": {
    width: 3,
    height: 5,
    panels: [
      { token: "S", x: 0, y: 0 },
      { token: "S", x: 1, y: 0 },
      { token: "b", x: 2, y: 0 },
      { token: "a", x: 0, y: 1 },
      { token: "S", x: 1, y: 1 },
      { token: "c", x: 2, y: 1 },
      { token: "S", x: 0.5, y: 2 },
      { token: "d", x: 0, y: 3 },
      { token: "S", x: 1, y: 3 },
      { token: "S", x: 2, y: 3 },
    ],
  },
  "3": {
    width: 3,
    height: 5,
    panels: [
      { token: "S", x: 0, y: 0 },
      { token: "S", x: 1, y: 0 },
      { token: "b", x: 2, y: 0 },
      { token: "S", x: 2, y: 1 },
      { token: "S", x: 1, y: 2 },
      { token: "c", x: 2, y: 2 },
      { token: "S", x: 2, y: 3 },
      { token: "d", x: 0, y: 4 },
      { token: "S", x: 1, y: 4 },
      { token: "c", x: 2, y: 4 },
    ],
  },
  "4": {
    width: 3,
    height: 5,
    panels: [
      { token: "S", x: 0, y: 0 },
      { token: "S", x: 2, y: 0 },
      { token: "S", x: 0, y: 1 },
      { token: "S", x: 2, y: 1 },
      { token: "d", x: 0, y: 2 },
      { token: "S", x: 1, y: 2 },
      { token: "S", x: 2, y: 2 },
      { token: "S", x: 2, y: 3 },
      { token: "S", x: 2, y: 4 },
    ],
  },
  "5": {
    width: 3,
    height: 5,
    panels: [
      { token: "a", x: 0, y: 0 },
      { token: "S", x: 1, y: 0 },
      { token: "S", x: 2, y: 0 },
      { token: "S", x: 0, y: 1 },
      { token: "d", x: 0, y: 2 },
      { token: "S", x: 1, y: 2 },
      { token: "b", x: 2, y: 2 },
      { token: "S", x: 2, y: 3 },
      { token: "d", x: 0, y: 4 },
      { token: "S", x: 1, y: 4 },
      { token: "c", x: 2, y: 4 },
    ],
  },
  "6": {
    width: 3,
    height: 5,
    panels: [
      { token: "a", x: 0, y: 0 },
      { token: "S", x: 1, y: 0 },
      { token: "b", x: 2, y: 0 },
      { token: "S", x: 0, y: 1 },
      { token: "d", x: 0, y: 2 },
      { token: "S", x: 1, y: 2 },
      { token: "b", x: 2, y: 2 },
      { token: "S", x: 0, y: 3 },
      { token: "S", x: 2, y: 3 },
      { token: "d", x: 0, y: 4 },
      { token: "S", x: 1, y: 4 },
      { token: "c", x: 2, y: 4 },
    ],
  },
  "7": {
    width: 2.5,
    height: 5,
    panels: [
      { token: "S", x: 1.5, y: 0 },
      { token: "S", x: 1.0, y: 1 },
      { token: "S", x: 0.5, y: 2 },
      { token: "S", x: 0.0, y: 3 },
    ],
  },
  "8": {
    width: 3,
    height: 5,
    panels: [
      { token: "a", x: 0, y: 0 },
      { token: "S", x: 1, y: 0 },
      { token: "b", x: 2, y: 0 },
      { token: "S", x: 0, y: 1 },
      { token: "S", x: 2, y: 1 },
      { token: "S", x: 0, y: 2 },
      { token: "S", x: 1, y: 2 },
      { token: "S", x: 2, y: 2 },
      { token: "S", x: 0, y: 3 },
      { token: "S", x: 2, y: 3 },
      { token: "d", x: 0, y: 4 },
      { token: "S", x: 1, y: 4 },
      { token: "c", x: 2, y: 4 },
    ],
  },
  "9": {
    width: 3,
    height: 5,
    panels: [
      { token: "a", x: 0, y: 0 },
      { token: "S", x: 1, y: 0 },
      { token: "b", x: 2, y: 0 },
      { token: "S", x: 0, y: 1 },
      { token: "S", x: 2, y: 1 },
      { token: "S", x: 0, y: 2 },
      { token: "S", x: 1, y: 2 },
      { token: "S", x: 2, y: 2 },
      { token: "S", x: 2, y: 3 },
      { token: "d", x: 0, y: 4 },
      { token: "S", x: 1, y: 4 },
      { token: "c", x: 2, y: 4 },
    ],
  },
  A: ["aSSb", "S..S", "SSSS", "S..S", "S..S"],
  B: {
    width: 4,
    height: 5,
    panels: [
      { token: "S", x: 0, y: 0 },
      { token: "S", x: 1, y: 0 },
      { token: "S", x: 2, y: 0 },
      { token: "b", x: 3, y: 0 },
      { token: "S", x: 0, y: 1 },
      { token: "S", x: 3, y: 1 },
      { token: "S", x: 0, y: 2 },
      { token: "S", x: 1, y: 2 },
      { token: "S", x: 2, y: 2 },
      { token: "S", x: 3, y: 2 },
      { token: "S", x: 0, y: 3 },
      { token: "S", x: 3, y: 3 },
      { token: "d", x: 0, y: 4 },
      { token: "S", x: 1, y: 4 },
      { token: "S", x: 2, y: 4 },
      { token: "c", x: 3, y: 4 },
    ],
  },
  C: ["aSSS", "S...", "S...", "S...", "dSSS"],
  D: {
    width: 4,
    height: 5,
    panels: [
      { token: "S", x: 0, y: 0 },
      { token: "S", x: 1, y: 0 },
      { token: "S", x: 2, y: 0 },
      { token: "b", x: 3, y: 0 },
      { token: "S", x: 0, y: 1 },
      { token: "S", x: 3, y: 1 },
      { token: "S", x: 0, y: 2 },
      { token: "S", x: 3, y: 2 },
      { token: "S", x: 0, y: 3 },
      { token: "S", x: 3, y: 3 },
      { token: "d", x: 0, y: 4 },
      { token: "S", x: 1, y: 4 },
      { token: "S", x: 2, y: 4 },
      { token: "c", x: 3, y: 4 },
    ],
  },
  E: {
    width: 4,
    height: 5,
    panels: [
      { token: "S", x: 0, y: 0 },
      { token: "S", x: 1, y: 0 },
      { token: "S", x: 2, y: 0 },
      { token: "C", x: 3, y: 0 },
      { token: "S", x: 0, y: 1 },
      { token: "S", x: 0, y: 2 },
      { token: "S", x: 1, y: 2 },
      { token: "S", x: 2, y: 2 },
      { token: "S", x: 0, y: 3 },
      { token: "S", x: 0, y: 4 },
      { token: "S", x: 1, y: 4 },
      { token: "S", x: 2, y: 4 },
      { token: "D", x: 3, y: 4 },
    ],
  },
  F: {
    width: 4,
    height: 5,
    panels: [
      { token: "S", x: 0, y: 0 },
      { token: "S", x: 1, y: 0 },
      { token: "S", x: 2, y: 0 },
      { token: "C", x: 3, y: 0 },
      { token: "S", x: 0, y: 1 },
      { token: "S", x: 0, y: 2 },
      { token: "S", x: 1, y: 2 },
      { token: "S", x: 2, y: 2 },
      { token: "S", x: 0, y: 3 },
      { token: "S", x: 0, y: 4 },
    ],
  },
  G: ["aSSb", "S...", "S.Sb", "S..S", "dSSc"],
  H: ["S..S", "S..S", "SSSS", "S..S", "S..S"],
  I: ["SSS", ".S.", ".S.", ".S.", "SSS"],
  J: ["..S", "..S", "..S", "..S", "dSS"],
  K: ["S..C", "S.B.", "SS..", "S.D.", "S..A"],
  L: ["S...", "S...", "S...", "S...", "dSSS"],
  M: ["S.B.S", "SBASB", "S.A.S", "S...S", "S...S"],
  N: ["SB..S", "S.B.S", "S..BS", "S...S", "S...S"],
  O: ["aSSb", "S..S", "S..S", "S..S", "dSSc"],
  P: ["aSSb", "S..S", "dSSc", "S...", "S..."],
  Q: ["aSSb", "S..S", "S..S", "S..S", "dSSD"],
  R: ["aSSb", "S..S", "dSSc", "S..B", "S...A"],
  S: ["aSSb", "S...", "dSSb", "...S", "dSSc"],
  T: {
    width: 4,
    height: 5,
    panels: [
      { token: "S", x: 0, y: 0 },
      { token: "S", x: 1, y: 0 },
      { token: "S", x: 2, y: 0 },
      { token: "S", x: 3, y: 0 },
      { token: "S", x: 1, y: 1 },
      { token: "S", x: 1, y: 2 },
      { token: "S", x: 1, y: 3 },
      { token: "S", x: 1, y: 4 },
    ],
  },
  U: ["S..S", "S..S", "S..S", "S..S", "dSSc"],
  V: {
    width: 4,
    height: 5,
    panels: [
      { token: "S", x: 0, y: 0 },
      { token: "S", x: 3, y: 0 },
      { token: "S", x: 0, y: 1 },
      { token: "S", x: 3, y: 1 },
      { token: "S", x: 0, y: 2 },
      { token: "S", x: 3, y: 2 },
      { token: "S", x: 1, y: 3 },
      { token: "S", x: 2, y: 3 },
      { token: "A", x: 1, y: 4 },
      { token: "C", x: 2, y: 4 },
    ],
  },
  W: {
    width: 5,
    height: 5,
    panels: [
      { token: "S", x: 0, y: 0 },
      { token: "S", x: 4, y: 0 },
      { token: "S", x: 0, y: 1 },
      { token: "S", x: 4, y: 1 },
      { token: "S", x: 0, y: 2 },
      { token: "S", x: 1, y: 2 },
      { token: "S", x: 3, y: 2 },
      { token: "S", x: 4, y: 2 },
      { token: "S", x: 0, y: 3 },
      { token: "B", x: 1, y: 3 },
      { token: "C", x: 3, y: 3 },
      { token: "S", x: 4, y: 3 },
      { token: "S", x: 0, y: 4 },
      { token: "A", x: 2, y: 4 },
      { token: "S", x: 4, y: 4 },
    ],
  },
  X: {
    width: 4,
    height: 5,
    panels: [
      { token: "B", x: 0, y: 0 },
      { token: "C", x: 3, y: 0 },
      { token: "S", x: 1, y: 1 },
      { token: "S", x: 2, y: 1 },
      { token: "S", x: 1, y: 2 },
      { token: "S", x: 2, y: 2 },
      { token: "A", x: 0, y: 3 },
      { token: "D", x: 3, y: 3 },
      { token: "S", x: 0, y: 4 },
      { token: "S", x: 3, y: 4 },
    ],
  },
  Y: {
    width: 2.5,
    height: 5,
    panels: [
      { token: "S", x: 0, y: 0 },
      { token: "S", x: 2, y: 0 },
      { token: "B", x: 0.5, y: 1 },
      { token: "C", x: 1.5, y: 1 },
      { token: "S", x: 1, y: 2 },
      { token: "S", x: 1, y: 3 },
      { token: "S", x: 1, y: 4 },
    ],
  },
  Z: {
    width: 4,
    height: 5,
    panels: [
      { token: "B", x: 0, y: 0 },
      { token: "S", x: 1, y: 0 },
      { token: "S", x: 2, y: 0 },
      { token: "S", x: 3, y: 0 },
      { token: "S", x: 2, y: 1 },
      { token: "S", x: 1, y: 2 },
      { token: "S", x: 0, y: 3 },
      { token: "S", x: 0, y: 4 },
      { token: "S", x: 1, y: 4 },
      { token: "S", x: 2, y: 4 },
      { token: "D", x: 3, y: 4 },
    ],
  },
  " ": ["..", "..", "..", "..", ".."],
};
